<a href="https://colab.research.google.com/github/hugochavezc/algebralineal/blob/main/ExamenTITULOAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algebra Lineal

### 1er examen parcial

EN este notebook deberás realizar cada uno de los ejercicios utilizando Python dentro de los bloques de código, si alguna salida requiere la visualización mediante Latex escribe el bloque correspondiente.

1. Genere los vectores $a$ y $ {b}$:

-   el vector ${a}$ está formado por la lista de números: 1, $\frac{1}{3}$, -5, π
-   el vector ${b}$ está formado por la lista de números: 1, $\frac{2}{3}$, 0.01,  $\sqrt 2$
-   súmelos

In [2]:
import numpy as np
a = np.array([1,1/3,-5, np.pi])
b = np.array([1,2/3,0.01, np.sqrt(2)])
suma = a + b
print("Vector a:", a)
print("Vector b:", b)
print("Suma de a y b:", suma)


Vector a: [ 1.          0.33333333 -5.          3.14159265]
Vector b: [1.         0.66666667 0.01       1.41421356]
Suma de a y b: [ 2.          1.         -4.99        4.55580622]


2. Proporcione ejemplos de matrices 3 por 3 no nulas de los siguientes
tipos de matrices:

-   Una matriz diagonal



In [3]:
import numpy as np
matriz_diagonal = np.diag([1, 2, 3])
print("Matriz diagonal:")
print(matriz_diagonal)


Matriz diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


-   Una matriz simétrica



In [4]:
import numpy as np
matriz_simetrica = np.array([
    [2, 3, 1],
    [3, 5, 4],
    [1, 4, 6]
])
print("Matriz simétrica:")
print(matriz_simetrica)


Matriz simétrica:
[[2 3 1]
 [3 5 4]
 [1 4 6]]


3. Cree la matriz
$${A}=\begin{bmatrix}1&0&0&7\\2&0&7&6\\-4&3&3&5\\0&3&4&-1\end{bmatrix}$$



Calcule el siguiente vector: 3 veces la primera columna de $A$
mas la segunda columna de $A$ menos 2 veces la tercera columna
menos 3 veces la última columna de $A$



In [5]:
import numpy as np
A = np.array([
    [1, 0, 0, 7],
    [2, 0, 7, 6],
    [-4, 3, 3, 5],
    [0, 3, 4, -1]
])
vector_resultado = 3 * A[:, 0] + A[:, 1] - 2 * A[:, 2] - 3 * A[:, 3]
print("Matriz A:")
print(A)
print("\nVector resultado:")
print(vector_resultado)


Matriz A:
[[ 1  0  0  7]
 [ 2  0  7  6]
 [-4  3  3  5]
 [ 0  3  4 -1]]

Vector resultado:
[-18 -26 -30  -2]


**4**.Genera la matriz identidad  I de rango 4 y 10


In [6]:
import numpy as np
I4 = np.identity(4)
I10 = np.identity(10)
print("Matriz identidad de rango 4:")
print(I4)
print("\nMatriz identidad de rango 10:")
print(I10)


Matriz identidad de rango 4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriz identidad de rango 10:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


5. Producto punto
Considere los vectores ${x}=(1, 1, -2)$, ${y}=(1, -2, 1)$
calcula el producto punto

In [7]:
import numpy as np
x = np.array([1, 1, -2])
y = np.array([1, -2, 1])
producto_punto = np.dot(x, y)
print("El producto punto de los vectores x e y es:", producto_punto)


El producto punto de los vectores x e y es: -3


6. Para la siguiente matriz $$\left[ \begin{array}{cccc}3&-2&2\\1&-1&-1\\2&1&2\\ \end{array} \right]$$ lleva a cabo el algoritmo de eliminación paso a paso.

Escribe en una celda separada cada operacion elemental.

In [8]:
import numpy as np
A = np.array([
    [3, -2, 2],
    [1, -1, -1],
    [2, 1, 2]
])
print("Matriz inicial:")
print(A)
A[1] = A[1] - (1/3) * A[0]
print("\nDespués de hacer que el elemento (2,1) sea 0:")
print(A)
A[2] = A[2] - (2/3) * A[0]
print("\nDespués de hacer que el elemento (3,1) sea 0:")
print(A)
A[2] = A[2] - (7) * A[1]
print("\nDespués de hacer que el elemento (3,2) sea 0:")
print(A)


Matriz inicial:
[[ 3 -2  2]
 [ 1 -1 -1]
 [ 2  1  2]]

Después de hacer que el elemento (2,1) sea 0:
[[ 3 -2  2]
 [ 0  0 -1]
 [ 2  1  2]]

Después de hacer que el elemento (3,1) sea 0:
[[ 3 -2  2]
 [ 0  0 -1]
 [ 0  2  0]]

Después de hacer que el elemento (3,2) sea 0:
[[ 3 -2  2]
 [ 0  0 -1]
 [ 0  2  7]]


7. Escriba las siguientes matrices elementales de orden 4.


(a) I τ
[(−2)1+3]

(b) I τ
[(0.5)1+4]

(c) I τ
[(-3)2+1]

(d) I τ
[(−10)3]

In [9]:
import numpy as np
I = np.identity(4)
E_a = I.copy()
E_a[2, 0] = -2
print("Matriz elemental (a):")
print(E_a)
E_b = I.copy()
E_b[3, 0] = 0.5
print("\nMatriz elemental (b):")
print(E_b)
E_c = I.copy()
E_c[0, 1] = -3
print("\nMatriz elemental (c):")
print(E_c)
E_d = I.copy()
E_d[2, 2] = -10
print("\nMatriz elemental (d):")
print(E_d)


Matriz elemental (a):
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-2.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Matriz elemental (b):
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.5 0.  0.  1. ]]

Matriz elemental (c):
[[ 1. -3.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Matriz elemental (d):
[[  1.   0.   0.   0.]
 [  0.   1.   0.   0.]
 [  0.   0. -10.   0.]
 [  0.   0.   0.   1.]]


8. Realiza el algoritmo de eliminación de Gauss-Jordan para la matriz del ejercicio 6, es decir continua las modificaciones de la matriz mediante operaciones elementales.
Por cada paso del algoritmo escribe la celda de código correspondiente.

In [10]:
import numpy as np
A = np.array([
    [3, -2, 2],
    [1, -1, -1],
    [2, 1, 2]
])
A[0] = A[0] / 3
print("Paso 1:\n", A)
A[1] = A[1] - A[0]
A[2] = A[2] - 2 * A[0]
print("Paso 2:\n", A)
A[1] = A[1] / (-1/3)
print("Paso 3:\n", A)
A[0] = A[0] + (2/3) * A[1]
A[2] = A[2] - (1/3) * A[1]
print("Paso 4:\n", A)
A[2] = A[2] / (-2/3)
print("Paso 5:\n", A)
A[0] = A[0] - (2/9) * A[2]
A[1] = A[1] + (4/9) * A[2]
print("Paso 6:\n", A)


Paso 1:
 [[ 1  0  0]
 [ 1 -1 -1]
 [ 2  1  2]]
Paso 2:
 [[ 1  0  0]
 [ 0 -1 -1]
 [ 0  1  2]]
Paso 3:
 [[1 0 0]
 [0 3 3]
 [0 1 2]]
Paso 4:
 [[1 2 2]
 [0 3 3]
 [0 0 1]]
Paso 5:
 [[ 1  2  2]
 [ 0  3  3]
 [ 0  0 -1]]
Paso 6:
 [[ 1  2  2]
 [ 0  3  2]
 [ 0  0 -1]]


9. Encuentra la inversa de la matriz del ejercicio 6.

In [14]:
import numpy as np
A = np.array([[3, -2, 2],
              [1, -1, -1],
              [2, 1, 2]])

A_inv = np.linalg.inv(A)
print("Inversa de A:")
print(A_inv)


Inversa de A:
[[-0.09090909  0.54545455  0.36363636]
 [-0.36363636  0.18181818  0.45454545]
 [ 0.27272727 -0.63636364 -0.09090909]]


10. Resuelva el siguiente sistema de ecuaciones:

$$ \begin{array}{ccc}5x&+7y&-z&=6\\2x&+10y&-2z&=4\\x&+y&+z&=0\\ \end{array} $$

In [16]:
import numpy as np
A = np.array([[5, 7, -1],
              [2, 10, -2],
              [1, 1, 1]])
b = np.array([6, 4, 0])
x = np.linalg.solve(A, b)
print(f"La solución del sistema es: x = {x[0]}, y = {x[1]}, z = {x[2]}")


La solución del sistema es: x = 1.0000000000000002, y = -1.2335811384723962e-16, z = -1.0000000000000002
